// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotaAlunoApi.Data;

#nullable disable

namespace NotaAlunoApi.Migrations
{
    [DbContext(typeof(AlunoContext))]
    [Migration("20230908193403_Adicionando Nota")]
    partial class AdicionandoNota
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NotaAlunoApi.Model.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NotaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotaId")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("NotaAlunoApi.Model.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ciencias")
                        .HasColumnType("int");

                    b.Property<int>("Geografia")
                        .HasColumnType("int");

                    b.Property<int>("Historia")
                        .HasColumnType("int");

                    b.Property<int>("Ingles")
                        .HasColumnType("int");

                    b.Property<int>("Matematica")
                        .HasColumnType("int");

                    b.Property<int>("Portugues")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("NotaAlunoApi.Model.Aluno", b =>
                {
                    b.HasOne("NotaAlunoApi.Model.Nota", "Nota")
                        .WithOne("Aluno")
                        .HasForeignKey("NotaAlunoApi.Model.Aluno", "NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("NotaAlunoApi.Model.Nota", b =>
                {
                    b.Navigation("Aluno")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
